"""add shares count

Revision ID: af89c271de98
Revises: 0001
Create Date: 2026-08-21 10:26:49.181358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shares_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shares_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.drop_column('shares_count')

    with op.batch_alter_table('reel_snapshots', schema=None) as batch_op:
        batch_op.drop_column('shares_count')

    # ### end Alembic commands ###
